### ISSUE TITLE
Windows 11, version 22H2

### ISSUE THREAD

**Issue by raloliver** [Naamloos/TopCenterStart11#18]
![22H2](https://user-images.githubusercontent.com/4580335/191660596-9eeb752e-8044-4117-aeec-b4ea04564b1a.png)

1. When I open the taskbar (by windows key), and the autohide is enabled, the taskbar scrolls down to the bottom (every time).
2. When I position the cursor on the taskbar the scrolling issue persists until I remove it.

![22H2](https://lrqv6a.dm.files.1drv.com/y4mDWnAdWPJ5ey8cn6bPSLsiqGGHfiU8OMTW3Y8SYwV3PcnOLfA3OvTa6u3yHu3XqCyZjhDkOwYg6MCaX09fDpirP1lX1o4xt4GGyyPgIOLiC-IwQxGyzRKt1Gy_r1Zgx6hBsUx0FVklBQqEp2CdpOOf_a-dTFmsdiCbn98IznL0VP81bRHud0gqIbJDviy3FyXWFoHbAh0CHklxFPe93istg/22H2.gif?psid=1)

**Comment by Naamloos** [comment]
I haven't personally tested against these cases yet. looks funny but obviously not the intended behavior. Will try and fix soon

**Comment by Maaaxx1** [comment]
Have the same issue at Win11 222H2 build 22621.674 (release)

**Comment by Naamloos** [comment]
Ah, my apologies. I completely forgot about this. I'll put down a reminder somewhere to take a look soon as I am currently working on my graduation internship a lot. :)

**Comment by Naamloos** [comment]
#20 should have added support for 22H2 :)

**Comment by Naamloos** [comment]
I'll be fixing some minor-ish bugs and release a new version soon.
