### ISSUE TITLE
Discussion: Moving taskbar to the top without involving registry

### ISSUE THREAD

**Issue by Naamloos** [Naamloos/TopCenterStart11#7]
Currently looking into options. Discussion is welcome. Posting some possible solutions here.

**Comment by Naamloos** [comment]
The windows taskbar appears to be a so-called "appbar", which has it's own APIs to manage and stuff (apart from window APIs).

This Shell API method may be relevant:
https://docs.microsoft.com/en-us/windows/win32/shell/abm-setpos

**Comment by Naamloos** [comment]
https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shappbarmessage

**Comment by Naamloos** [comment]
This may or may not also be interesting to @jetspiking

**Comment by Naamloos** [comment]
> https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shappbarmessage

This may be the one, though we'll have to request app bar data from the system still to move the taskbar.
I think

**Comment by jetspiking** [comment]
I do not have a lot of experience with using the C++ Windows calls directly. How could we get a pointer or reference to the taskbar without knowing the name?

**Comment by Naamloos** [comment]
The name is Shell_TrayWnd and the title is empty. Issue being that windows seems to ignore most calls to move the taskbar. 

trying out the following in a bit:
https://groups.google.com/g/microsoft.public.platformsdk.shell/c/jGn92w4ztKU
(Also tasked archive.org with creating a backup in the waybackmachine, as google likes to kill old services and this post seems promising.)

**Comment by Naamloos** [comment]
I'll play around with in in a bit.

by the way, if you want any help at some point with your app feel free to hit me up. Especially after I fix this. :)

**Comment by jetspiking** [comment]
Sure! You are also very welcome to create a pull request for Taskbar11, that way you are added as a contributor and also get credit for your work. We can also program together using Discord / Teams / etc, let me know. :)

**Comment by Naamloos** [comment]
I've been fairly inactive considering I'm busy with school right now. I'll let you know when I find some time to work on this :p

**Comment by Naamloos** [comment]
@jetspiking if I find out something I can always port the "hack" (let's be honest, it's a hack) to your app :p

**Comment by jetspiking** [comment]
@Naamloos Same :smile:. No worries and good luck! Some things are simply more important.

**Comment by Naamloos** [comment]
Added priority: high because this issue is breaking.

**Comment by Naamloos** [comment]
@jetspiking grand news: I managed to do it on the latest insider build!
![image](https://user-images.githubusercontent.com/12187179/159031822-8ebac127-8460-4780-97fc-2210c0e2dcde.png)

**Comment by Naamloos** [comment]
I'm pushing these changes right now, but I'll rewrite the whole project in C# because it's just easier to manage for me.

**Comment by Naamloos** [comment]
issue here being windows snap too high..

**Comment by jetspiking** [comment]
Great job @Naamloos ! Seems like Taskbar11 should also use this solution  :)

**Comment by Naamloos** [comment]
got that figured out as well. last issue is desktop icons, but I'm fine fixing that after the .NET port.
![image](https://user-images.githubusercontent.com/12187179/159050031-1de3c114-f36a-4a40-811e-0e03856f4b7f.png)

**Comment by Naamloos** [comment]
fixed that as well. last issue is desktop icon alignment
![image](https://user-images.githubusercontent.com/12187179/159050137-95f40e20-04d4-4e9b-b8ba-f7a349e2c739.png)

**Comment by Naamloos** [comment]
Issue has been resolved on rewrite branch (C#).
